### ISSUE TITLE
suggestion: adding offline search functionality

### ISSUE THREAD

**Issue by Simplenuity** [linuxlite/litemanual#7]
As [discussed on the forum](https://www.linuxliteos.com/forums/suggestions-and-feedback/help-manual-suggestions-wanted/msg28279/#msg28279) I'd like to suggest the implementation of a search functionality.

This would greatly enhance the usability of the Help Manual.

It would need to be an offline solution to make it independent from internet access.

Thank you for your consideration.

**Comment by Simplenuity** [comment]
I just came across [Fullproof](https://reyesr.github.io/fullproof/)
Might that tick the boxes?

**Comment by linuxlite** [comment]
@Simplenuity thanks, I'll check that out.

**Comment by linuxlite** [comment]
Feature added.
